name: google
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  # APIs
  http: ^1.2.2

  # Platform
  speech_to_text: ^7.0.0
  flutter_tts: 3.8.5

  # Storage
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.2.1

  # Cloud
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4

  # UI
  modal_progress_hud_nsn: ^0.5.1
  flutter_spinkit: ^5.2.1
  animated_text_kit: ^4.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/profile/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700